create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  user_id text,
  items jsonb not null,
  amount numeric not null default 0,
  address jsonb,
  status text not null default 'Order Placed',
  payment_method text,
  payment_status text,
  timeline jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- Development policy for this app because it currently uses Clerk/local users,
-- not Supabase Auth users. Tighten these policies before production.
create policy "Allow public order inserts"
on public.orders
for insert
to anon
with check (true);

create policy "Allow public order reads"
on public.orders
for select
to anon
using (true);
